### ISSUE TITLE
我用本地部署提示这些错误可能是什么原因呢？

### ISSUE THREAD

**Issue by jiburan999888** [dreamhunter2333/chatgpt-tarot-divination#41]
root@iZt4naudvth5fc699pje2kZ:~/chatgpt-tarot-divination-main# ./venv/bin/python3 main.py
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from router.chatgpt_router import router as chatgpt_router
  File "/root/chatgpt-tarot-divination-main/router/chatgpt_router.py", line 17, in <module>
    from .divination import DivinationFactory
  File "/root/chatgpt-tarot-divination-main/router/divination/__init__.py", line 1, in <module>
    from . import base
  File "/root/chatgpt-tarot-divination-main/router/divination/base.py", line 16, in <module>
    class DivinationFactory(metaclass=MetaDivination):
  File "/root/chatgpt-tarot-divination-main/router/divination/base.py", line 25, in DivinationFactory
    def build_prompt(self, divination_body: DivinationBody) -> tuple[str, str]:
TypeError: 'type' object is not subscriptable

**Comment by dreamhunter2333** [comment]
python 版本是多少呢，测试 python3.9 + 应该没问题
